spring:
  jpa:
    generate-ddl: true

  application:
    name=wordle
  datasource:
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wordle

  logging:
    level:
      sql: INFO