spring:
  application:
    name=wordle

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wordle

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  logging:
    level:
      sql: INFO