spring:
  jpa:
    generate-ddl: true

  application:
    name=wordle
  datasource:
    url: jdbc:postgresql://localhost:5432/DB_Words
    username: admin
    password: admin
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update




  logging:
    level:
      sql: INFO