spring:
  jpa:
    generate-ddl: true

  application:
    name=wordle
  datasource:
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update

  logging:
    level:
      sql: INFO